// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UretimMaliyet.Data;

#nullable disable

namespace UretimMaliyet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715104130_Kullanici")]
    partial class Kullanici
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("UretimMaliyet.Models.Hammadde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Birim")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StokMiktari")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hammaddeler");
                });

            modelBuilder.Entity("UretimMaliyet.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("UretimMaliyet.Models.ReceteKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HammaddeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HammaddeId");

                    b.HasIndex("UrunId");

                    b.ToTable("ReceteKalemleri");
                });

            modelBuilder.Entity("UretimMaliyet.Models.UretimEmri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamMaliyet")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("UretimEmirleri");
                });

            modelBuilder.Entity("UretimMaliyet.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("UretimMaliyet.Models.ReceteKalemi", b =>
                {
                    b.HasOne("UretimMaliyet.Models.Hammadde", "Hammadde")
                        .WithMany()
                        .HasForeignKey("HammaddeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UretimMaliyet.Models.Urun", "Urun")
                        .WithMany("ReceteKalemleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hammadde");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("UretimMaliyet.Models.UretimEmri", b =>
                {
                    b.HasOne("UretimMaliyet.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("UretimMaliyet.Models.Urun", b =>
                {
                    b.Navigation("ReceteKalemleri");
                });
#pragma warning restore 612, 618
        }
    }
}
